### ISSUE TITLE
CORS  No 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by FadySamirSadek** [contributor-ninja/contributor.ninja#18]
<img width="1920" alt="screen shot 2018-06-09 at 3 00 21 am" src="https://user-images.githubusercontent.com/7483806/41186121-63e24a4c-6b91-11e8-9ea4-806e07ef3bc8.png">

**Comment by xtuc** [comment]
Thanks for the report. 

I have touble finding the time to fix this, would you mind sending a PR?

**Comment by FadySamirSadek** [comment]
@xtuc no problem, will open a PR soon
