### ISSUE TITLE
Reduce permissions asked for login

### ISSUE THREAD

**Issue by waldyrious** [contributor-ninja/contributor.ninja#7]
This level of access seems quite extreme:

![screenshot from 2017-12-22 09-15-27](https://user-images.githubusercontent.com/478237/34292560-504c0db4-e6f9-11e7-9862-476ca9fe231f.png)

Could you at least explain why those permissions are needed?

**Comment by xtuc** [comment]
Thanks for the PR. 

I'm really sorry about that, Contributor-ninja shouldn't require any special information from GitHub (maybe only your public email address).

The code is here https://github.com/contributor-ninja/contributor.ninja/blob/master/src/Components/Login.js#L6 and it seems that it has a bug in it.

Would you be open to make a PR to fix that?

**Comment by xtuc** [comment]
cc @qZzQ1 if you'd like to look at it

**Comment by waldyrious** [comment]
Thanks for the fast response. Unfortunately I don't have any experience interfacing with Github's permissions system, and at the moment don't have the availability to research the topic. But if you give me some pointers on what the correct code should be, I'd be happy to submit a PR :)

**Comment by waldyrious** [comment]
Thanks for the fast response. Unfortunately I don't have any experience interfacing with Github's permissions system, and at the moment don't have the availability to research the topic. But if you give me some pointers on what the correct code should look like, I'd be happy to submit a PR :)

**Comment by xtuc** [comment]
Ok, it's live (modulo the browser/CDN cache).

This is what it looks like now:
![screenshot from 2017-12-22 17-35-19](https://user-images.githubusercontent.com/1493671/34305703-a1a5bb56-e73f-11e7-8e0d-0ea787a6eba9.png)

Probably less scary :smile:
