### ISSUE TITLE
Blur does not disappear after login

### ISSUE THREAD

**Issue by waldyrious** [contributor-ninja/contributor.ninja#9]
On the right side:

![screenshot from 2017-12-22 17-01-14](https://user-images.githubusercontent.com/478237/34306285-58807c54-e73a-11e7-9e39-b1d2a5a6a354.png)

**Comment by xtuc** [comment]
That's actually not a bug, you can't add new columns at the moment because the feature isn't developed.

**Comment by waldyrious** [comment]
Ah, got it :) thanks for the clarification. But perhaps consider greying out the button (it can be done quite easily via css, with `filter: saturate(0);`), and adding a tooltip explaining why it's disabled, rather than using a blur. IMHO that would communicate the disabled status more effectively.

**Comment by zumpiez** [comment]
@waldyrious But it's already gray in the screenshot you posted.

**Comment by waldyrious** [comment]
I meant the entire object, including the black tooltip. I was suggesting a native tooltip (using the `title` attribute) that would appear when the user hovers over that element, explaining that the feature is not available yet. I get that this is a minor UI concern, but blurring doesn't communicate "intentionally disabled" to me, and left me confused about whether it could be a bug.

Now, whether resolving this potential for confusion is something that's worth prioritizing, considering the current state of the rest of the project, its a decision I leave to you :)

**Comment by xtuc** [comment]
@waldyrious I agree with your point!

I removed the blur and added "soon":

![screenshot from 2017-12-23 14-21-37](https://user-images.githubusercontent.com/1493671/34319870-b1113dce-e7ec-11e7-955f-d32d74d3658f.png)

Does it make sense to you now?

**Comment by waldyrious** [comment]
Yeah, that's perfectly clear :) thanks!

**Comment by xtuc** [comment]
It's live (modulo caches)!
